name: flutter_qr_demo
description: Demo project for the Flutter QR library.

dependencies:
  flutter:
    sdk: flutter
  qr_flutter:
    path: ..
  keyboard_visibility: ^0.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false
  assets:
    - assets/images/ic_submit.png
  fonts:
    - family: "Inconsolata"
      fonts:
        - asset: assets/fonts/Inconsolata-Regular.ttf