name: flutter_qr_demo
description: Demo project for the Flutter QR library.

dependencies:
  flutter:
    sdk: flutter
  qr_flutter:
    path: ..
  provider: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false
  assets:
    - assets/images/ic_submit.png
    - assets/images/ic_error_correct.png
    - assets/images/ic_version_circle.png
  fonts:
    - family: "Inconsolata"
      fonts:
        - asset: assets/fonts/Inconsolata-Regular.ttf
